//! Construction of the byte strings the user's identity key signs and
//! Play Integrity's `requestHash` binds.
//!
//! **This module is the normative side of the Android wire contract.**
//! Unlike the DeviceCheck profile — where the Swift client existed
//! first and the backend pinned fixtures generated from it — no Android
//! client existed when this profile was implemented, so the fixtures in
//! `android/fixtures/` are generated *here* and the Kotlin client must
//! reproduce them byte-for-byte (Moderation-Device-Recall.md §8 gap 11).
//! Regenerate them from this module — never by hand — if the format
//! ever changes, and version the context strings when it does.
//!
//! Layout: for each field in order — context, challenge (raw bytes),
//! user key, ISO 8601 timestamp, mandate ref (empty when absent) — a
//! big-endian `u32` length followed by the raw bytes. Length prefixes
//! make the concatenation injective, so no two different field splits
//! can collide, and the leading context string domain-separates
//! enrollment from gate-check so neither signature can be replayed as
//! the other (or against the iOS contexts, which spell differently).
//!
//! The integrity token itself is **not** a field: it does not exist
//! until after the hash is computed. The token binds to this payload
//! through `requestHash` — Google echoes the hash the app passed to
//! `setRequestHash`, and the backend recomputes it from the transmitted
//! fields — while the identity signature covers the same bytes
//! directly. Two bindings, one payload.

use sha2::{Digest, Sha256};

pub const ENROLL_CONTEXT: &str = "onym-moderation-android-enroll-v1";
pub const GATE_CONTEXT: &str = "onym-moderation-android-gate-v1";

fn append(out: &mut Vec<u8>, field: &[u8]) {
    out.extend_from_slice(&(field.len() as u32).to_be_bytes());
    out.extend_from_slice(field);
}

fn bytes(
    context: &str,
    challenge: &[u8],
    user_key: &str,
    timestamp: &str,
    mandate_ref: Option<&str>,
) -> Vec<u8> {
    let mut out = Vec::new();
    append(&mut out, context.as_bytes());
    append(&mut out, challenge);
    append(&mut out, user_key.as_bytes());
    append(&mut out, timestamp.as_bytes());
    append(&mut out, mandate_ref.unwrap_or("").as_bytes());
    out
}

/// Signed bytes for `POST /v1/enroll`.
pub fn enrollment(challenge: &[u8], user_key: &str, timestamp: &str) -> Vec<u8> {
    bytes(ENROLL_CONTEXT, challenge, user_key, timestamp, None)
}

/// Signed bytes for `POST /v1/gate-check`.
pub fn gate_check(
    challenge: &[u8],
    user_key: &str,
    mandate_ref: Option<&str>,
    timestamp: &str,
) -> Vec<u8> {
    bytes(GATE_CONTEXT, challenge, user_key, timestamp, mandate_ref)
}

/// The `requestHash` the app passes to Play Integrity for this payload:
/// base64url (no padding) of SHA-256 over the signed bytes. 43
/// characters — comfortably inside Google's 500-byte limit.
pub fn request_hash(payload: &[u8]) -> String {
    use base64::Engine;
    base64::engine::general_purpose::URL_SAFE_NO_PAD.encode(Sha256::digest(payload))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn fields_are_length_prefixed_big_endian() {
        let out = enrollment(b"ab", "k", "t");
        // context(33) + challenge(2) + userKey(1) + timestamp(1) +
        // mandateRef(0), each with a 4-byte prefix.
        assert_eq!(out.len(), 4 * 5 + ENROLL_CONTEXT.len() + 2 + 1 + 1);
        assert_eq!(&out[0..4], &(ENROLL_CONTEXT.len() as u32).to_be_bytes());
    }

    /// The property length-prefixing exists for: no two different field
    /// splits may produce the same bytes.
    #[test]
    fn field_boundaries_are_unambiguous() {
        assert_ne!(enrollment(b"ab", "c", "t"), enrollment(b"a", "bc", "t"));
    }

    #[test]
    fn enrollment_and_gate_payloads_are_domain_separated() {
        assert_ne!(enrollment(b"c", "u", "ts"), gate_check(b"c", "u", None, "ts"));
    }

    /// The Android contexts must never collide with the iOS ones —
    /// a signature minted for one profile is inert against the other.
    #[test]
    fn contexts_are_distinct_from_the_ios_profile() {
        assert_ne!(ENROLL_CONTEXT, "onym-moderation-enroll-v1");
        assert_ne!(GATE_CONTEXT, "onym-moderation-gate-v1");
    }

    #[test]
    fn gate_payload_covers_mandate_ref() {
        assert_ne!(
            gate_check(b"c", "u", Some("mandate-a"), "ts"),
            gate_check(b"c", "u", Some("mandate-b"), "ts")
        );
    }

    // ─── Frozen cross-implementation fixtures ────────────────────────
    //
    // These hex strings are the normative Android wire contract,
    // generated by THIS module and mirrored in `android/fixtures/`
    // (Moderation-Device-Recall.md §8 gap 11: the fixtures must be
    // published before a client implements them). The Kotlin client's
    // `SignedSessionPayload` must reproduce them byte-for-byte;
    // regenerate from here — never by hand — if the format changes.
    //
    //   timestamp "2026-08-08T12:00:00Z", userKey "onym:key:aabb",
    //   challenge = the 32 bytes 0x00..0x1f, mandateRef "mandate-ref-1"

    const TS: &str = "2026-08-08T12:00:00Z";
    const USER_KEY: &str = "onym:key:aabb";

    fn challenge() -> Vec<u8> {
        (0u8..32).collect()
    }

    #[test]
    fn enrollment_fixture_is_frozen() {
        let expected = "000000216f6e796d2d6d6f6465726174696f6e2d616e64726f69642d656e726f\
6c6c2d763100000020000102030405060708090a0b0c0d0e0f10111213141516\
1718191a1b1c1d1e1f0000000d6f6e796d3a6b65793a61616262000000143230\
32362d30382d30385431323a30303a30305a00000000";
        let payload = enrollment(&challenge(), USER_KEY, TS);
        assert_eq!(hex::encode(&payload), expected);
        assert_eq!(request_hash(&payload), "MjdGYuAzA2yGT0TFKvav9Iopz4YbP0keGnh61SJ1QPU");
    }

    #[test]
    fn gate_check_fixture_is_frozen() {
        let expected = "0000001f6f6e796d2d6d6f6465726174696f6e2d616e64726f69642d67617465\
2d763100000020000102030405060708090a0b0c0d0e0f101112131415161718\
191a1b1c1d1e1f0000000d6f6e796d3a6b65793a616162620000001432303236\
2d30382d30385431323a30303a30305a0000000d6d616e646174652d7265662d\
31";
        let payload = gate_check(&challenge(), USER_KEY, Some("mandate-ref-1"), TS);
        assert_eq!(hex::encode(&payload), expected);
        assert_eq!(request_hash(&payload), "faELd9vZwOtBP14VochzXfc08GopZmrZCc8XeVD6jkY");
    }

    /// Enrollment has no mandate yet; the trailing slot encodes empty.
    #[test]
    fn gate_check_without_mandate_ref_fixture_is_frozen() {
        let expected = "0000001f6f6e796d2d6d6f6465726174696f6e2d616e64726f69642d67617465\
2d763100000020000102030405060708090a0b0c0d0e0f101112131415161718\
191a1b1c1d1e1f0000000d6f6e796d3a6b65793a616162620000001432303236\
2d30382d30385431323a30303a30305a00000000";
        let payload = gate_check(&challenge(), USER_KEY, None, TS);
        assert_eq!(hex::encode(&payload), expected);
        assert_eq!(request_hash(&payload), "kuaMPqtf-bLFKROyTPUnD_4TdyJ9ImSQOuEDzMbbfK4");
    }
}
