//! Finalize the published manifest for discovery-seat review.
//!
//! The clients' destination-manifest review (Android
//! `ServiceManifestReviewer`, its iOS equivalent, and the normative
//! `onym-discovery` reference) only trusts a manifest that carries an
//! **embedded** `signature`: Ed25519 by the manifest's own `operator`
//! key over the canonical bytes — the document with the top-level
//! `signature` field removed **structurally**, re-serialized compact
//! with every object's keys sorted by UTF-8 byte order. The discovery
//! catalog additionally reads a human-readable top-level `name` and
//! `endpoints: [{"uri": …}]`.
//!
//! This module produces exactly the bytes `onym-discovery`'s
//! `sign-manifest` would emit for the same content and key: the served
//! bytes ARE the canonical bytes plus the `signature` field, which
//! sorts into place like any other key. The agreement is pinned by the
//! fixtures in `fixtures/discovery-destination-*.json`, generated with
//! `onym-discovery sign-manifest` — if either implementation drifts,
//! the byte-equality test below fails.
//!
//! The detached `manifest.json.sig` flow is untouched and separate:
//! it signs the *final* file bytes (embedded signature included), so
//! it is produced after this step, by `sign-manifest`.

use ed25519_dalek::Signer;
use serde_json::{json, Value};

use crate::util;

/// Default human-readable name a finalized manifest carries when the
/// source declares none.
pub const DEFAULT_MANIFEST_NAME: &str = "Onym Authority";

/// Default public base URL for the injected `endpoints` entry when the
/// source declares none.
pub const DEFAULT_PUBLIC_URL: &str = "https://authority.onym.app";

/// Produce the final publishable manifest bytes: inject `name` and
/// `endpoints` when the source omits them, then embed the operator
/// signature over the canonical signing bytes.
///
/// Fields the source already declares are never overridden — an
/// operator who authored their own `name` or `endpoints` keeps them.
/// Any pre-existing `signature` is replaced: it covered different
/// bytes.
///
/// Refuses when the manifest's `operator` is not the key `seed`
/// derives — an embedded signature the named key cannot verify would
/// make every reviewing client reject the manifest, which is strictly
/// worse than publishing without one.
pub fn finalize_manifest(
    raw: &[u8],
    name: &str,
    endpoint_uri: &str,
    seed: &[u8; 32],
) -> Result<Vec<u8>, String> {
    let mut value: Value =
        serde_json::from_slice(raw).map_err(|e| format!("malformed JSON: {e}"))?;
    let object = value
        .as_object_mut()
        .ok_or_else(|| "top level is not a JSON object".to_string())?;

    let key = ed25519_dalek::SigningKey::from_bytes(seed);
    let signing_reference = util::key_reference(key.verifying_key().as_bytes());
    match object.get("operator").and_then(Value::as_str) {
        Some(operator) if operator == signing_reference => {}
        Some(operator) => {
            return Err(format!(
                "the manifest's `operator` is {operator} but this seed signs as \
                 {signing_reference}; refusing to embed a signature no reviewer could verify"
            ))
        }
        None => return Err("manifest has no `operator` field".into()),
    }

    if !object.contains_key("name") {
        object.insert("name".into(), Value::String(name.into()));
    }
    if !object.contains_key("endpoints") {
        object.insert("endpoints".into(), json!([{ "uri": endpoint_uri }]));
    }
    // Structurally, never by string surgery — same rule as
    // `canonical.rs`, same reason: textual removal is forgeable.
    object.remove("signature");

    // `serde_json::Value` objects are BTreeMaps, so this is compact,
    // key-sorted (UTF-8 byte order), `/` unescaped — the profile's
    // canonical form.
    let signing_bytes =
        serde_json::to_vec(&value).map_err(|e| format!("serialize signing bytes: {e}"))?;
    let signature = util::base64_encode(&key.sign(&signing_bytes).to_bytes());
    value
        .as_object_mut()
        .expect("top level was an object above")
        .insert("signature".into(), Value::String(signature));
    serde_json::to_vec(&value).map_err(|e| format!("serialize manifest: {e}"))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::types::AuthorityManifest;

    /// The fixture pair pinning cross-implementation byte agreement:
    /// `discovery-destination-signed.json` was generated by
    /// `onym-discovery sign-manifest` (the normative discovery
    /// reference) from `discovery-destination-input.json` with the
    /// all-`0x11` seed. Byte equality here proves the embedded
    /// signature covers exactly the canonical form the discovery
    /// profile defines.
    const INPUT: &[u8] = include_bytes!("../fixtures/discovery-destination-input.json");
    const SIGNED: &[u8] = include_bytes!("../fixtures/discovery-destination-signed.json");
    const SEED: [u8; 32] = [0x11; 32];

    fn object(bytes: &[u8]) -> serde_json::Map<String, Value> {
        serde_json::from_slice::<Value>(bytes).unwrap().as_object().unwrap().clone()
    }

    #[test]
    fn matches_onym_discovery_sign_manifest_byte_for_byte() {
        let out = finalize_manifest(INPUT, "ignored", "https://ignored.example", &SEED).unwrap();
        assert_eq!(out, SIGNED);
    }

    /// The same bytes must come out when `name` and `endpoints` are
    /// injected rather than authored: injection happens before
    /// canonicalization, so an injected field is indistinguishable
    /// from an authored one.
    #[test]
    fn injected_name_and_endpoints_reproduce_the_fixture() {
        let mut value: Value = serde_json::from_slice(INPUT).unwrap();
        let object = value.as_object_mut().unwrap();
        object.remove("name");
        object.remove("endpoints");
        let stripped = serde_json::to_vec(&value).unwrap();
        let out =
            finalize_manifest(&stripped, "Onym Authority", "https://authority.onym.app", &SEED)
                .unwrap();
        assert_eq!(out, SIGNED);
    }

    /// A reviewer's check, reproduced end to end: decode the embedded
    /// signature, rebuild the canonical bytes (signature removed
    /// structurally, sorted, compact), verify against the `operator`
    /// key from the manifest itself.
    #[test]
    fn embedded_signature_verifies_over_canonical_bytes() {
        use base64::Engine as _;
        use ed25519_dalek::Verifier;

        let out = finalize_manifest(INPUT, "n", "https://e", &SEED).unwrap();
        let object = object(&out);
        let signature_b64 = object["signature"].as_str().unwrap().to_string();
        let operator = object["operator"].as_str().unwrap();
        let key_bytes: [u8; 32] = hex::decode(operator.strip_prefix("onym:key:").unwrap())
            .unwrap()
            .try_into()
            .unwrap();

        let canonical = crate::canonical::canonical_bytes(&out, &["signature"]).unwrap();
        let signature = ed25519_dalek::Signature::from_bytes(
            &base64::engine::general_purpose::STANDARD
                .decode(signature_b64)
                .unwrap()
                .try_into()
                .unwrap(),
        );
        ed25519_dalek::VerifyingKey::from_bytes(&key_bytes)
            .unwrap()
            .verify(&canonical, &signature)
            .unwrap();
    }

    /// Authored fields survive; only `signature` is replaced.
    #[test]
    fn authored_name_and_endpoints_are_never_overridden() {
        let raw = br#"{"operator":"onym:key:d04ab232742bb4ab3a1368bd4615e4e6d0224ab71a016baf8520a332c9778737","name":"Custom","endpoints":[{"uri":"https://custom.example"}],"signature":"stale"}"#;
        let object = object(&finalize_manifest(raw, "Onym Authority", "https://a", &SEED).unwrap());
        assert_eq!(object["name"], "Custom");
        assert_eq!(object["endpoints"][0]["uri"], "https://custom.example");
        assert_ne!(object["signature"], "stale");
    }

    #[test]
    fn refuses_a_seed_the_manifest_does_not_name() {
        let error = finalize_manifest(INPUT, "n", "https://e", &[0x22; 32]).unwrap_err();
        assert!(error.contains("operator"), "{error}");
    }

    /// The reference template, finalized, still parses as an
    /// `AuthorityManifest` whose policy terms validate — the fields
    /// this step adds must never break the moderation clients or the
    /// boot checks that read the same bytes.
    #[test]
    fn finalized_reference_template_remains_a_valid_authority_manifest() {
        let template = include_str!("../manifest/manifest.json").replace(
            "onym:key:0000000000000000000000000000000000000000000000000000000000000000",
            "onym:key:d04ab232742bb4ab3a1368bd4615e4e6d0224ab71a016baf8520a332c9778737",
        );
        let out = finalize_manifest(
            template.as_bytes(),
            DEFAULT_MANIFEST_NAME,
            DEFAULT_PUBLIC_URL,
            &SEED,
        )
        .unwrap();
        let manifest: AuthorityManifest = serde_json::from_slice(&out).unwrap();
        manifest.validate_class_terms().unwrap();
        assert!(manifest.signature.is_some());
        let object = object(&out);
        assert_eq!(object["name"], DEFAULT_MANIFEST_NAME);
        assert_eq!(object["endpoints"][0]["uri"], DEFAULT_PUBLIC_URL);
    }
}
